/**
 * Worker entry source code generator.
 *
 * Generates a CF Workers entry that statically imports all Next.js
 * page/route handlers. With --webpack, .next/server/app/*.js are
 * standard CJS modules that esbuild can bundle.
 */

import type { NextAdapter } from "next";

type BuildContext = Parameters<NonNullable<NextAdapter["onBuildComplete"]>>[0];

export interface WorkerEntryOptions {
  buildId: string;
  routing: BuildContext["routing"];
  outputs: BuildContext["outputs"];
  basePath: string;
  /** Embedded manifests: absolute path → file content */
  manifests: Record<string, string>;
  /** Prerender entries for ISR cache seeding */
  prerenderEntries: Array<{
    pathname: string;
    html: string;
    postponedState?: string;
    initialRevalidate?: number | false;
    initialStatus?: number;
    initialHeaders?: Record<string, string | string[]>;
    pprHeaders?: Record<string, string>;
  }>;
}

interface HandlerEntry {
  pathname: string;
  importPath: string;
  varName: string;
  runtime: "nodejs" | "edge";
  type: string;
}

/**
 * Generate the worker entry source code.
 * All handler modules are statically imported so esbuild bundles them.
 */
export function generateWorkerEntry(opts: WorkerEntryOptions): string {
  const handlers = collectHandlers(opts.outputs);
  const pathnames = collectPathnames(opts.outputs);

  // Lazy imports — used at request time, not module evaluation.
  // wrangler bundles the entry + all reachable imports.
  const handlerEntries = handlers
    .map(
      (h) =>
        `  ${JSON.stringify(h.pathname)}: { load: () => import(${JSON.stringify(h.importPath)}), runtime: ${JSON.stringify(h.runtime)}, type: ${JSON.stringify(h.type)} },`,
    )
    .join("\n");

  // Collect client-reference-manifest JS files from build output.
  // These set globalThis.__RSC_MANIFEST[page] = { ... } which the
  // Next.js renderer needs for React Server Components.
  const manifestImports = collectManifestPaths(opts.outputs)
    .map((p) => `import ${JSON.stringify(p)};`)
    .join("\n");

  return `
// Generated by adapter-creek — do not edit
import { resolveRoutes, responseToMiddlewareResult } from "@next/routing";
import { DurableObject } from "cloudflare:workers";

${opts.outputs.middleware?.edgeRuntime ? `
// Load edge middleware module — populates globalThis._ENTRIES
import ${JSON.stringify(opts.outputs.middleware.edgeRuntime.modulePath)};
` : ""}
// DO class stubs — required by control-plane for Next.js ISR bindings.
export class DOQueueHandler extends DurableObject {}
export class DOShardedTagCache extends DurableObject {}
export class BucketCachePurge extends DurableObject {}

const BUILD_ID = ${JSON.stringify(opts.buildId)};
const BASE_PATH = ${JSON.stringify(opts.basePath)};
const ROUTING = ${JSON.stringify(opts.routing)};
const PATHNAMES = ${JSON.stringify(pathnames)};

// Embedded manifests — Next.js route modules call loadManifest() which
// normally uses fs.readFileSync(). Expose on globalThis so the shim can access it.
globalThis.__MANIFESTS = ${JSON.stringify(opts.manifests)};

// Prerender entries for ISR cache seeding (PPR shells + static prerenders)
const __PRERENDER_ENTRIES = ${JSON.stringify(opts.prerenderEntries)};

// Initialize manifests singleton — called lazily on first SSR request.
function __initManifests() {
  const MANIFESTS_SINGLETON = Symbol.for('next.server.manifests');
  if (globalThis[MANIFESTS_SINGLETON]) return;

  // Parse client-reference manifests from embedded data.
  // The JS files have format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
  // We extract the JSON object directly via regex instead of eval.
  globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {};
  const manifests = globalThis.__MANIFESTS || {};
  for (const [key, content] of Object.entries(manifests)) {
    if (!key.includes("client-reference-manifest.js")) continue;
    try {
      // Format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
      // Find the second assignment (the one with the page key)
      const idx = content.lastIndexOf('__RSC_MANIFEST[');
      if (idx >= 0) {
        // Extract page key between ["..."]
        const keyStart = content.indexOf('"', idx);
        const keyEnd = content.indexOf('"', keyStart + 1);
        const page = content.slice(keyStart + 1, keyEnd);
        // Extract JSON after ]=
        const jsonStart = content.indexOf(']=', keyEnd) + 2;
        let jsonStr = content.slice(jsonStart);
        if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
        globalThis.__RSC_MANIFEST[page] = JSON.parse(jsonStr);
      }
    } catch {}
  }

  {
    // Parse server-reference-manifest for server actions
    let serverActionsManifest = { encryptionKey: "", node: {}, edge: {} };
    try {
      const raw = globalThis.__MANIFESTS && Object.entries(globalThis.__MANIFESTS)
        .find(([k]) => k.includes("server-reference-manifest.json"));
      if (raw) serverActionsManifest = JSON.parse(raw[1]);
    } catch {}

    // Initialize with empty client reference map (pages will register via __RSC_MANIFEST)
    const clientReferenceManifestsPerRoute = new Map();
    const rscManifest = globalThis.__RSC_MANIFEST || {};
    for (const [page, manifest] of Object.entries(rscManifest)) {
      // __RSC_MANIFEST keys are like "/page", "/pricing/page", "/docs/[[...slug]]/page"
      // workStore.route uses "/", "/pricing", "/docs/[[...slug]]"
      const normalized = page.replace(/\\/page$/, "").replace(/^$/, "/");
      clientReferenceManifestsPerRoute.set(normalized, manifest);
      // Also keep the original key for direct lookups
      clientReferenceManifestsPerRoute.set(page, manifest);
    }

    // Create proxy for client references
    const proxiedClientReferenceManifest = new Proxy({}, {
      get(_, prop) {
        if (prop === "clientModules" || prop === "rscModuleMapping" || prop === "ssrModuleMapping" ||
            prop === "edgeRscModuleMapping" || prop === "edgeSSRModuleMapping") {
          return new Proxy({}, {
            get(__, id) {
              for (const manifest of clientReferenceManifestsPerRoute.values()) {
                if (manifest && manifest[prop] && manifest[prop][id]) return manifest[prop][id];
              }
              return undefined;
            }
          });
        }
        if (prop === "moduleLoading" || prop === "entryCSSFiles" || prop === "entryJSFiles") {
          const first = clientReferenceManifestsPerRoute.values().next().value;
          return first ? first[prop] : undefined;
        }
        return undefined;
      }
    });

    globalThis[MANIFESTS_SINGLETON] = {
      clientReferenceManifestsPerRoute,
      proxiedClientReferenceManifest,
      serverActionsManifest: {
        encryptionKey: serverActionsManifest.encryptionKey || "",
        node: Object.assign(Object.create(null), serverActionsManifest.node || {}),
        edge: Object.assign(Object.create(null), serverActionsManifest.edge || {}),
      },
      serverModuleMap: new Proxy({}, {
        get: (_, id) => {
          const workers = serverActionsManifest.node?.[id]?.workers;
          if (!workers) return undefined;
          const entry = Object.values(workers)[0];
          return entry ? { id: entry.moduleId, name: id, chunks: [], async: entry.async } : undefined;
        }
      }),
    };
  }

  // Seed ISR cache with prerender entries from build output.
  // This provides instant responses for statically prerendered pages
  // and PPR shells, matching the behavior of next start.
  if (__PRERENDER_ENTRIES.length > 0 && typeof globalThis.__CREEK_CACHE === "undefined") {
    globalThis.__CREEK_CACHE = new Map();
    for (const entry of __PRERENDER_ENTRIES) {
      globalThis.__CREEK_CACHE.set(entry.pathname, {
        value: {
          kind: "APP_PAGE",
          html: entry.html,
          postponed: entry.postponedState,
          status: entry.initialStatus,
          headers: entry.initialHeaders,
        },
        lastModified: Date.now(),
        revalidate: typeof entry.initialRevalidate === "number" ? entry.initialRevalidate : undefined,
      });
    }
  }
}


const HANDLERS = {
${handlerEntries}
};

// Middleware handler — invoked by @next/routing when a request matches
// middleware matchers. Uses the edge runtime _ENTRIES pattern.
${opts.outputs.middleware && opts.outputs.middleware.runtime === "edge" && opts.outputs.middleware.edgeRuntime ? `
const middlewareHandler = async (mwCtx) => {
  try {
    const entry = globalThis._ENTRIES?.[${JSON.stringify(opts.outputs.middleware.edgeRuntime.entryKey)}];
    if (!entry) return {};
    const handler = entry[${JSON.stringify(opts.outputs.middleware.edgeRuntime.handlerExport)}];
    if (typeof handler !== "function") return {};
    const response = await handler(
      new Request(mwCtx.url, {
        method: "GET",
        headers: mwCtx.headers,
        body: mwCtx.requestBody,
      }),
      {}
    );
    return responseToMiddlewareResult(response);
  } catch {
    return {};
  }
};
` : `const middlewareHandler = async () => ({});`}

// --- Node.js bridge ---
${NODE_BRIDGE_CODE}

export default {
  async fetch(request, env, ctx) {
    try {
      __initManifests();
      const url = new URL(request.url);

      // 1. Static assets via WfP ASSETS binding
      if (url.pathname.startsWith("/_next/static/")) {
        return env.ASSETS.fetch(request);
      }

      // 2. Try serving as static asset
      try {
        const assetRes = await env.ASSETS.fetch(
          new Request(new URL(url.pathname, url.origin), { headers: request.headers })
        );
        if (assetRes.ok) return assetRes;
      } catch {}

      // 3. Route resolution via @next/routing
      const result = await resolveRoutes({
        url: new URL(request.url),
        buildId: BUILD_ID,
        basePath: BASE_PATH,
        headers: request.headers,
        requestBody: request.body,
        pathnames: PATHNAMES,
        routes: ROUTING,
        invokeMiddleware: middlewareHandler,
      });

      if (result.redirect) {
        return Response.redirect(result.redirect.url.toString(), result.redirect.status);
      }
      if (result.middlewareResponded) {
        return new Response(null, { status: 204 });
      }

      // 4. Invoke matched handler
      const resolvedPathname = result.resolvedPathname;
      if (!resolvedPathname || !HANDLERS[resolvedPathname]) {
        try {
          const notFound = await env.ASSETS.fetch(new Request(new URL("/404.html", url.origin)));
          return new Response(notFound.body, { status: 404, headers: notFound.headers });
        } catch {
          return new Response("Not Found", { status: 404 });
        }
      }

      const handler = HANDLERS[resolvedPathname];
      const mod = await handler.load();

      if (handler.runtime === "edge") {
        const fn = mod.default || mod.handler;
        if (typeof fn === "function") {
          return fn(request, { waitUntil: ctx.waitUntil.bind(ctx) });
        }
      }

      // Streaming SSR: use TransformStream so chunks flow to the client
      // as Next.js writes them, enabling Server Components streaming,
      // PPR shell delivery, and progressive HTML rendering.
      return await invokeNodeHandler(request, mod, ctx);
    } catch (err) {
      const msg = err instanceof Error ? (err.stack || err.message) : String(err);
      return new Response(JSON.stringify({ error: "ssr_error", message: msg }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
`;
}

function collectHandlers(outputs: BuildContext["outputs"]): HandlerEntry[] {
  const handlers: HandlerEntry[] = [];
  const seen = new Set<string>();
  let idx = 0;

  const addOutput = (
    output: { pathname: string; filePath: string; runtime: "nodejs" | "edge" },
    type: string,
  ) => {
    if (output.pathname.endsWith(".rsc")) return;
    if (seen.has(output.pathname)) return;
    seen.add(output.pathname);

    handlers.push({
      pathname: output.pathname,
      importPath: output.filePath,
      varName: `_h${idx++}`,
      runtime: output.runtime,
      type,
    });
  };

  for (const page of outputs.appPages) addOutput(page, "APP_PAGE");
  for (const route of outputs.appRoutes) addOutput(route, "APP_ROUTE");
  for (const page of outputs.pages) addOutput(page, "PAGES");
  for (const api of outputs.pagesApi) addOutput(api, "PAGES_API");

  return handlers;
}

/**
 * Find client-reference-manifest JS files in the build output.
 * These are generated per-page in .next/server/app/<page>/page_client-reference-manifest.js
 * and set globalThis.__RSC_MANIFEST[page] when executed.
 */
function collectManifestPaths(outputs: BuildContext["outputs"]): string[] {
  const paths: string[] = [];
  const seen = new Set<string>();

  for (const page of outputs.appPages) {
    if (page.pathname.endsWith(".rsc")) continue;

    // The manifest file is next to the page handler:
    // .next/server/app/<page>/page.js → page_client-reference-manifest.js
    const dir = page.filePath.replace(/\/page\.js$/, "");
    const manifestPath = dir + "/page_client-reference-manifest.js";
    if (!seen.has(manifestPath)) {
      seen.add(manifestPath);
      paths.push(manifestPath);
    }
  }

  return paths;
}

function collectPathnames(outputs: BuildContext["outputs"]): string[] {
  const pathnames = new Set<string>();
  for (const p of outputs.appPages) pathnames.add(p.pathname);
  for (const r of outputs.appRoutes) pathnames.add(r.pathname);
  for (const p of outputs.pages) pathnames.add(p.pathname);
  for (const a of outputs.pagesApi) pathnames.add(a.pathname);
  for (const s of outputs.staticFiles) pathnames.add(s.pathname);
  return [...pathnames];
}

const NODE_BRIDGE_CODE = `
import { IncomingMessage, ServerResponse } from "http";

/**
 * Streaming SSR bridge: Web Request -> IncomingMessage/ServerResponse -> Web Response.
 *
 * Uses TransformStream to stream chunks to the client as Next.js writes them.
 * The Response is returned as soon as headers are sent (writeHead/first write),
 * enabling Server Components streaming, PPR, and progressive rendering.
 */
async function invokeNodeHandler(request, mod, ctx) {
  const url = new URL(request.url);

  // Build IncomingMessage
  const req = new IncomingMessage();
  req.method = request.method;
  req.url = url.pathname + url.search;
  req.headers = Object.fromEntries(request.headers);
  if (request.body) {
    const reader = request.body.getReader();
    (async () => {
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) { req.push(null); break; }
          req.push(value);
        }
      } catch { req.push(null); }
    })();
  } else {
    req.push(null);
  }

  // Build ServerResponse with streaming output
  const res = new ServerResponse(req);
  const { readable, writable } = new TransformStream();
  const writer = writable.getWriter();

  // resolveResponse is called when we have enough info to return a Response
  // (status + headers). The body streams via the readable side.
  let resolveResponse;
  const responsePromise = new Promise((resolve) => { resolveResponse = resolve; });
  let headersFlushed = false;

  function flushHeaders() {
    if (headersFlushed) return;
    headersFlushed = true;
    resolveResponse(new Response(readable, {
      status: res.statusCode,
      statusText: res.statusMessage || "",
      headers: res.getHeaders(),
    }));
  }

  // Intercept write — stream chunks to the client immediately
  res.write = function(chunk, encoding, cb) {
    if (typeof encoding === "function") { cb = encoding; encoding = undefined; }
    if (!headersFlushed) flushHeaders();
    if (chunk) {
      if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
      writer.write(chunk);
    }
    if (cb) cb();
    return true;
  };

  // Intercept end — flush final chunk and close the stream
  res.end = function(chunk, encoding, cb) {
    if (typeof chunk === "function") { cb = chunk; chunk = null; }
    if (typeof encoding === "function") { cb = encoding; encoding = null; }
    if (!headersFlushed) flushHeaders();
    if (chunk) {
      if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
      writer.write(chunk);
    }
    writer.close().catch(() => {});
    res.finished = true;
    res.emit("finish");
    res.emit("close");
    if (cb) cb();
    return res;
  };

  // Intercept writeHead to flush headers early (enables 103 Early Hints)
  const origWriteHead = res.writeHead.bind(res);
  res.writeHead = function(...args) {
    origWriteHead(...args);
    flushHeaders();
    return res;
  };

  // Invoke the handler — try multiple export patterns:
  // - mod.handler: standard Next.js handler export (app pages, routes)
  // - mod.routeModule.handle: route module instance method
  // - mod.default: default export (some module formats)
  // - mod.GET/POST/etc: App Route HTTP method handlers (route.ts)
  let handlerFn = mod.handler
    || mod.routeModule?.handle?.bind(mod.routeModule)
    || mod.default;

  // For App Routes that export HTTP methods directly
  if (typeof handlerFn !== "function" && (mod.GET || mod.POST || mod.PUT || mod.DELETE || mod.PATCH)) {
    const method = request.method.toUpperCase();
    const methodHandler = mod[method];
    if (typeof methodHandler === "function") {
      // App Route handlers return Response directly (Web API)
      writer.close().catch(() => {});
      const response = await methodHandler(request);
      return response;
    }
  }

  if (typeof handlerFn !== "function") {
    writer.close().catch(() => {});
    throw new Error("No handler function found on module (keys: " + Object.keys(mod).join(",") + ")");
  }

  const handlerResult = handlerFn(req, res, {
    waitUntil: (p) => ctx.waitUntil(p.catch(() => {})),
    requestMeta: {
      relativeProjectDir: ".",
      hostname: request.headers.get("host") || "localhost",
    },
  });

  // Swallow handler rejection to prevent CF Workers 1101.
  // The actual response data is captured via res.write/end.
  if (handlerResult?.then) {
    handlerResult.catch((err) => {
      if (!res.finished) {
        res.statusCode = 500;
        res.end(JSON.stringify({ error: "render_error", message: err instanceof Error ? err.message : String(err) }));
      }
    });
  }

  // Wait for the Response to be created (headers flushed), with timeout
  const response = await Promise.race([
    responsePromise,
    new Promise((_, reject) => setTimeout(() => {
      writer.close().catch(() => {});
      reject(new Error("SSR timeout: no response headers within 25s"));
    }, 25000)),
  ]);

  return response;
}
`;
