/**
 * Worker entry source code generator.
 *
 * Generates a CF Workers entry that statically imports all Next.js
 * page/route handlers. With --webpack, .next/server/app/*.js are
 * standard CJS modules that esbuild can bundle.
 */

import { existsSync } from "node:fs";
import * as path from "node:path";
import type { NextAdapter } from "next";

type BuildContext = Parameters<NonNullable<NextAdapter["onBuildComplete"]>>[0];

export interface WorkerEntryOptions {
  buildId: string;
  routing: BuildContext["routing"];
  outputs: BuildContext["outputs"];
  basePath: string;
  /** Embedded manifests: absolute path → file content */
  manifests: Record<string, string>;
  /** Path to Turbopack runtime file (for static import to trigger chunk bundling) */
  turbopackRuntimePath?: string;
  /** Prerender entries for ISR cache seeding */
  prerenderEntries: Array<{
    pathname: string;
    html: string;
    postponedState?: string;
    initialRevalidate?: number | false;
    initialStatus?: number;
    initialHeaders?: Record<string, string | string[]>;
    pprHeaders?: Record<string, string>;
  }>;
}

interface HandlerEntry {
  pathname: string;
  importPath: string;
  varName: string;
  runtime: "nodejs" | "edge";
  type: string;
  edgeRuntime?: {
    entryKey: string;
    handlerExport: string;
  };
}

/**
 * Generate the worker entry source code.
 * All handler modules are statically imported so esbuild bundles them.
 */
export function generateWorkerEntry(opts: WorkerEntryOptions): string {
  const handlers = collectHandlers(opts.outputs);
  const pathnames = collectPathnames(opts.outputs);
  const staticPageMap = collectStaticPageMap(opts.outputs);

  // Lazy imports — used at request time, not module evaluation.
  // wrangler bundles the entry + all reachable imports.
  const handlerEntries = handlers
    .map(
      (h) => {
        const parts = [
          `load: () => import(${JSON.stringify(h.importPath)})`,
          `runtime: ${JSON.stringify(h.runtime)}`,
          `type: ${JSON.stringify(h.type)}`,
        ];
        if (h.edgeRuntime) {
          parts.push(`entryKey: ${JSON.stringify(h.edgeRuntime.entryKey)}`);
          parts.push(`handlerExport: ${JSON.stringify(h.edgeRuntime.handlerExport)}`);
        }
        return `  ${JSON.stringify(h.pathname)}: { ${parts.join(", ")} },`;
      },
    )
    .join("\n");

  // Collect client-reference-manifest JS files from build output.
  // These set globalThis.__RSC_MANIFEST[page] = { ... } which the
  // Next.js renderer needs for React Server Components.
  const manifestImports = collectManifestPaths(opts.outputs)
    .map((p) => `import ${JSON.stringify(p)};`)
    .join("\n");

  return `
// Generated by adapter-creek — do not edit
// Polyfill globalThis.AsyncLocalStorage BEFORE any Next.js code runs.
// Next.js checks globalThis.AsyncLocalStorage to decide whether to use
// a real or fake implementation. CF Workers has it via node:async_hooks
// but not on globalThis by default.
import { AsyncLocalStorage } from "node:async_hooks";
if (!globalThis.AsyncLocalStorage) globalThis.AsyncLocalStorage = AsyncLocalStorage;

// Polyfill process methods and env that Next.js uses.
if (typeof process !== "undefined") {
  if (!process.env) process.env = {};
  if (!process.env.NODE_ENV) process.env.NODE_ENV = "production";
  if (!process.env.NEXT_RUNTIME) process.env.NEXT_RUNTIME = "nodejs";
  if (!process.version) process.version = "v20.0.0";
  if (!process.versions) process.versions = { node: "20.0.0" };
  if (!process.cwd) process.cwd = () => "/";
  if (!process.hrtime) {
    process.hrtime = Object.assign((prev) => {
      const now = performance.now();
      const sec = Math.floor(now / 1000);
      const nsec = Math.floor((now % 1000) * 1e6);
      if (prev) return [sec - prev[0], nsec - prev[1]];
      return [sec, nsec];
    }, { bigint: () => BigInt(Math.floor(performance.now() * 1e6)) });
  }
  if (!process.on) process.on = () => process;
  if (!process.removeListener) process.removeListener = () => process;
  if (!process.off) process.off = () => process;
}

import { resolveRoutes, responseToMiddlewareResult } from "@next/routing";
import { DurableObject } from "cloudflare:workers";

${opts.turbopackRuntimePath ? `
// Import Turbopack runtime statically so wrangler bundles all chunks.
// The runtime's requireChunk() switch was patched to inline all chunk paths.
import ${JSON.stringify(opts.turbopackRuntimePath)};
` : ""}
${opts.outputs.middleware?.edgeRuntime ? `
// Load edge middleware module — populates globalThis._ENTRIES
import ${JSON.stringify(opts.outputs.middleware.edgeRuntime.modulePath)};
` : ""}
// Import client-reference manifests — these set globalThis.__RSC_MANIFEST[page]
// which the Next.js renderer needs for React Server Components.
${manifestImports}

// DO class stubs — required by control-plane for Next.js ISR bindings.
export class DOQueueHandler extends DurableObject {}
export class DOShardedTagCache extends DurableObject {}
export class BucketCachePurge extends DurableObject {}

const BUILD_ID = ${JSON.stringify(opts.buildId)};
const BASE_PATH = ${JSON.stringify(opts.basePath)};
const ROUTING = ${JSON.stringify(opts.routing)};
const PATHNAMES = ${JSON.stringify(pathnames)};

// Static page map: request pathname → asset file path.
// Pages Router static pages and auto-statically-optimized pages don't work
// through handler invocation in CF Workers (no filesystem access).
const STATIC_PAGES = ${JSON.stringify(staticPageMap)};

// Embedded manifests — Next.js route modules call loadManifest() which
// normally uses fs.readFileSync(). Expose on globalThis so the shim can access it.
globalThis.__MANIFESTS = ${JSON.stringify(opts.manifests)};

// Prerender entries for ISR cache seeding (PPR shells + static prerenders)
const __PRERENDER_ENTRIES = ${JSON.stringify(opts.prerenderEntries)};

// Initialize manifests singleton — called lazily on first SSR request.
function __initManifests() {
  const MANIFESTS_SINGLETON = Symbol.for('next.server.manifests');
  if (globalThis[MANIFESTS_SINGLETON]) return;

  // Parse client-reference manifests from embedded data.
  // The JS files have format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
  // We extract the JSON object directly via regex instead of eval.
  globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {};
  const manifests = globalThis.__MANIFESTS || {};
  for (const [key, content] of Object.entries(manifests)) {
    if (!key.includes("client-reference-manifest.js")) continue;
    try {
      // Format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
      // Find the second assignment (the one with the page key)
      const idx = content.lastIndexOf('__RSC_MANIFEST[');
      if (idx >= 0) {
        // Extract page key between ["..."]
        const keyStart = content.indexOf('"', idx);
        const keyEnd = content.indexOf('"', keyStart + 1);
        const page = content.slice(keyStart + 1, keyEnd);
        // Extract JSON after ]=
        const jsonStart = content.indexOf(']=', keyEnd) + 2;
        let jsonStr = content.slice(jsonStart);
        if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
        globalThis.__RSC_MANIFEST[page] = JSON.parse(jsonStr);
      }
    } catch {}
  }

  {
    // Parse server-reference-manifest for server actions
    let serverActionsManifest = { encryptionKey: "", node: {}, edge: {} };
    try {
      const raw = globalThis.__MANIFESTS && Object.entries(globalThis.__MANIFESTS)
        .find(([k]) => k.includes("server-reference-manifest.json"));
      if (raw) serverActionsManifest = JSON.parse(raw[1]);
    } catch {}

    // Initialize with empty client reference map (pages will register via __RSC_MANIFEST)
    const clientReferenceManifestsPerRoute = new Map();
    const rscManifest = globalThis.__RSC_MANIFEST || {};
    for (const [page, manifest] of Object.entries(rscManifest)) {
      // __RSC_MANIFEST keys are like "/page", "/pricing/page", "/docs/[[...slug]]/page"
      // workStore.route uses "/", "/pricing", "/docs/[[...slug]]"
      const normalized = page.replace(/\\/page$/, "").replace(/^$/, "/");
      clientReferenceManifestsPerRoute.set(normalized, manifest);
      // Also keep the original key for direct lookups
      clientReferenceManifestsPerRoute.set(page, manifest);
    }

    // Create proxy for client references
    const proxiedClientReferenceManifest = new Proxy({}, {
      get(_, prop) {
        if (prop === "clientModules" || prop === "rscModuleMapping" || prop === "ssrModuleMapping" ||
            prop === "edgeRscModuleMapping" || prop === "edgeSSRModuleMapping") {
          return new Proxy({}, {
            get(__, id) {
              for (const manifest of clientReferenceManifestsPerRoute.values()) {
                if (manifest && manifest[prop] && manifest[prop][id]) return manifest[prop][id];
              }
              return undefined;
            }
          });
        }
        if (prop === "moduleLoading" || prop === "entryCSSFiles" || prop === "entryJSFiles") {
          const first = clientReferenceManifestsPerRoute.values().next().value;
          return first ? first[prop] : undefined;
        }
        return undefined;
      }
    });

    globalThis[MANIFESTS_SINGLETON] = {
      clientReferenceManifestsPerRoute,
      proxiedClientReferenceManifest,
      serverActionsManifest: {
        encryptionKey: serverActionsManifest.encryptionKey || "",
        node: Object.assign(Object.create(null), serverActionsManifest.node || {}),
        edge: Object.assign(Object.create(null), serverActionsManifest.edge || {}),
      },
      serverModuleMap: new Proxy({}, {
        get: (_, id) => {
          const workers = serverActionsManifest.node?.[id]?.workers;
          if (!workers) return undefined;
          const entry = Object.values(workers)[0];
          return entry ? { id: entry.moduleId, name: id, chunks: [], async: entry.async } : undefined;
        }
      }),
    };
  }

  // Seed ISR cache with prerender entries from build output.
  // This provides instant responses for statically prerendered pages
  // and PPR shells, matching the behavior of next start.
  if (__PRERENDER_ENTRIES.length > 0 && typeof globalThis.__CREEK_CACHE === "undefined") {
    globalThis.__CREEK_CACHE = new Map();
    for (const entry of __PRERENDER_ENTRIES) {
      globalThis.__CREEK_CACHE.set(entry.pathname, {
        value: {
          kind: "APP_PAGE",
          html: entry.html,
          postponed: entry.postponedState,
          status: entry.initialStatus,
          headers: entry.initialHeaders,
        },
        lastModified: Date.now(),
        revalidate: typeof entry.initialRevalidate === "number" ? entry.initialRevalidate : undefined,
      });
    }
  }
}


const HANDLERS = {
${handlerEntries}
};

// Middleware handler — invoked by @next/routing when a request matches
// middleware matchers. Uses the edge runtime _ENTRIES pattern.
${opts.outputs.middleware && opts.outputs.middleware.runtime === "edge" && opts.outputs.middleware.edgeRuntime ? `
const middlewareHandler = async (mwCtx) => {
  try {
    const entry = globalThis._ENTRIES?.[${JSON.stringify(opts.outputs.middleware.edgeRuntime.entryKey)}];
    if (!entry) return {};
    const handler = entry[${JSON.stringify(opts.outputs.middleware.edgeRuntime.handlerExport)}];
    if (typeof handler !== "function") return {};
    const mwReq = new Request(mwCtx.url, {
      method: mwCtx.requestBody ? "POST" : "GET",
      headers: mwCtx.headers,
      body: mwCtx.requestBody,
    });
    const response = await handler(mwReq, {});
    return responseToMiddlewareResult(response, mwCtx.headers, mwCtx.url);
  } catch {
    return {};
  }
};
` : `const middlewareHandler = async () => ({});`}

// --- Node.js bridge ---
${NODE_BRIDGE_CODE}

export default {
  async fetch(request, env, ctx) {
    try {
      __initManifests();
      const url = new URL(request.url);

      // 1. Static assets via WfP ASSETS binding
      // /_next/data/ requests are Pages Router data fetches — must go through routing
      if (url.pathname.startsWith("/_next/") && !url.pathname.startsWith("/_next/data/")) {
        try {
          const assetRes = await env.ASSETS.fetch(request);
          if (assetRes.ok) return assetRes;
        } catch {}
        // Fall through to routing for _next/image etc.
      }

      // 2. Image optimization — proxy to original image.
      // Full optimization (resize/format) will use CF Image Resizing in production.
      if (url.pathname === "/_next/image") {
        const imageUrl = url.searchParams.get("url");
        if (imageUrl) {
          try {
            // Internal images — serve from assets
            if (imageUrl.startsWith("/")) {
              const assetRes = await env.ASSETS.fetch(
                new Request(new URL(imageUrl, url.origin), { headers: request.headers })
              );
              if (assetRes.ok) {
                const headers = new Headers(assetRes.headers);
                headers.set("Cache-Control", "public, max-age=60");
                return new Response(assetRes.body, { status: 200, headers });
              }
            }
            // External images — proxy
            if (imageUrl.startsWith("http")) {
              const imgRes = await fetch(imageUrl);
              if (imgRes.ok) return imgRes;
            }
          } catch {}
        }
        return new Response("Image not found", { status: 404 });
      }

      // 3. Route resolution via @next/routing
      // Clone request for routing — middleware may read the body, but the
      // original must remain available for the handler (server actions, POST).
      const routingClone = request.body ? request.clone() : request;
      let result = await resolveRoutes({
        url: new URL(request.url),
        buildId: BUILD_ID,
        basePath: BASE_PATH,
        headers: routingClone.headers,
        requestBody: routingClone.body,
        pathnames: PATHNAMES,
        routes: ROUTING,
        invokeMiddleware: middlewareHandler,
      });

      if (result.redirect) {
        // Use manual Response — Response.redirect() may not support all status codes (e.g., 308)
        return new Response(null, {
          status: result.redirect.status,
          headers: { Location: result.redirect.url.toString() },
        });
      }
      if (result.middlewareResponded) {
        return new Response(null, { status: 204 });
      }
      if (result.externalRewrite) {
        return fetch(result.externalRewrite.toString(), {
          method: request.method,
          headers: request.headers,
          body: request.body,
        });
      }

      // Strip Next.js internal sentinel values from route matches.
      // $nxtPrest is used for optional catch-all [[...rest]] when no params present.
      if (result.routeMatches) {
        for (const [key, val] of Object.entries(result.routeMatches)) {
          if (val === "$nxtPrest" || val === "%24nxtPrest") {
            result = { ...result, routeMatches: { ...result.routeMatches, [key]: "" } };
          }
        }
      }

      // 4. Resolve handler pathname
      let resolvedPathname = result.resolvedPathname;
      // resolveRoutes may return invocationTarget with the actual pathname to invoke.
      if (!resolvedPathname && result.invocationTarget?.pathname) {
        const target = result.invocationTarget.pathname;
        if (HANDLERS[target]) resolvedPathname = target;
      }
      // If resolvedPathname has .rsc suffix, try without it
      if (resolvedPathname && !HANDLERS[resolvedPathname] && resolvedPathname.endsWith(".rsc")) {
        const withoutRsc = resolvedPathname.slice(0, -4);
        if (HANDLERS[withoutRsc]) resolvedPathname = withoutRsc;
      }
      // Try index route: /foo → /foo/index or /foo/page
      if (resolvedPathname && !HANDLERS[resolvedPathname]) {
        if (HANDLERS[resolvedPathname + "/index"]) resolvedPathname = resolvedPathname + "/index";
      }

      // 4a. Static pages — serve pre-rendered HTML from assets.
      // Pages Router static pages and auto-optimized pages are pre-rendered
      // at build time. Their handlers require filesystem access that CF Workers
      // doesn't have, so we serve the HTML directly from assets.
      const servePath = resolvedPathname || url.pathname;
      const staticAssetPath = STATIC_PAGES[servePath];
      if (staticAssetPath) {
        try {
          const assetRes = await env.ASSETS.fetch(
            new Request(new URL(staticAssetPath, url.origin), { headers: request.headers })
          );
          if (assetRes.ok) {
            const headers = new Headers(assetRes.headers);
            headers.set("Content-Type", "text/html; charset=utf-8");
            // Apply middleware resolved headers if present
            if (result.resolvedHeaders) {
              result.resolvedHeaders.forEach((val, key) => {
                if (key.toLowerCase() === "set-cookie") headers.append(key, val);
                else headers.set(key, val);
              });
            }
            return new Response(assetRes.body, {
              status: result.status || 200,
              headers,
            });
          }
        } catch {}
      }

      // 4b. If no route handler matched, check for static assets or 404.
      if (!resolvedPathname || !HANDLERS[resolvedPathname]) {
        // Try static assets — for paths with extensions (JS, CSS, images)
        // or paths that might be stored in assets.
        try {
          const assetRes = await env.ASSETS.fetch(
            new Request(new URL(url.pathname, url.origin), { headers: request.headers })
          );
          if (assetRes.ok) return assetRes;
        } catch {}

        // Fall back to SSR _not-found handler or static 404
        if (HANDLERS["/_not-found"]) {
          resolvedPathname = "/_not-found";
          // Force 404 status — the handler renders the not-found boundary
          // but doesn't know the original request was unmatched.
          if (!result.status) result = { ...result, status: 404 };
        } else {
          // Try static 404 page from assets
          const notFoundPath = STATIC_PAGES["/404"] || "/404/index.html";
          try {
            const notFound = await env.ASSETS.fetch(new Request(new URL(notFoundPath, url.origin)));
            if (notFound.ok) {
              return new Response(notFound.body, { status: 404, headers: notFound.headers });
            }
          } catch {}
          return new Response("Not Found", { status: 404 });
        }
      }

      const handler = HANDLERS[resolvedPathname];
      const mod = await handler.load();

      if (handler.runtime === "edge") {
        // Edge runtime handlers register in globalThis._ENTRIES when their
        // module is loaded. Use the entryKey/handlerExport metadata to invoke
        // them through the official Next.js edge entry registry.
        if (handler.entryKey) {
          await handler.load(); // Trigger module registration in _ENTRIES
          const entry = globalThis._ENTRIES?.[handler.entryKey];
          if (entry) {
            const fn = entry[handler.handlerExport || "handler"];
            if (typeof fn === "function") {
              return fn(request, { waitUntil: ctx.waitUntil.bind(ctx) });
            }
          }
        }
        // Fallback: try direct module exports
        const fn = typeof mod.default === "function" ? mod.default
          : typeof mod.default?.default === "function" ? mod.default.default
          : mod.handler;
        if (typeof fn === "function") {
          return fn(request, { waitUntil: ctx.waitUntil.bind(ctx) });
        }
      }

      // Streaming SSR: use TransformStream so chunks flow to the client
      // as Next.js writes them, enabling Server Components streaming,
      // PPR shell delivery, and progressive HTML rendering.
      return await invokeNodeHandler(request, mod, ctx, result);
    } catch (err) {
      const msg = err instanceof Error ? (err.stack || err.message) : String(err);
      return new Response(JSON.stringify({ error: "ssr_error", message: msg }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
`;
}

function collectHandlers(outputs: BuildContext["outputs"]): HandlerEntry[] {
  const handlers: HandlerEntry[] = [];
  const seen = new Set<string>();
  let idx = 0;

  const addOutput = (
    output: {
      pathname: string;
      filePath: string;
      runtime: "nodejs" | "edge";
      edgeRuntime?: { modulePath: string; entryKey: string; handlerExport: string };
    },
    type: string,
  ) => {
    if (output.pathname.endsWith(".rsc")) return;
    if (seen.has(output.pathname)) return;
    seen.add(output.pathname);

    const entry: HandlerEntry = {
      pathname: output.pathname,
      importPath: output.edgeRuntime?.modulePath || output.filePath,
      varName: `_h${idx++}`,
      runtime: output.runtime,
      type,
    };
    if (output.edgeRuntime) {
      entry.edgeRuntime = {
        entryKey: output.edgeRuntime.entryKey,
        handlerExport: output.edgeRuntime.handlerExport,
      };
    }
    handlers.push(entry);
  };

  for (const page of outputs.appPages) addOutput(page, "APP_PAGE");
  for (const route of outputs.appRoutes) addOutput(route, "APP_ROUTE");
  for (const page of outputs.pages) addOutput(page, "PAGES");
  for (const api of outputs.pagesApi) addOutput(api, "PAGES_API");

  return handlers;
}

/**
 * Find client-reference-manifest JS files in the build output.
 * These are generated per-page in .next/server/app/<page>/page_client-reference-manifest.js
 * and set globalThis.__RSC_MANIFEST[page] when executed.
 */
function collectManifestPaths(outputs: BuildContext["outputs"]): string[] {
  const paths: string[] = [];
  const seen = new Set<string>();

  for (const page of outputs.appPages) {
    if (page.pathname.endsWith(".rsc")) continue;
    // Skip edge runtime pages — their manifest paths use a different structure
    // (.next/server/edge/chunks/ssr/...) that doesn't contain manifest files.
    if (page.runtime === "edge") continue;

    // The manifest file is next to the page handler:
    // .next/server/app/<page>/page.js → page_client-reference-manifest.js
    const dir = page.filePath.replace(/\/page\.js$/, "");
    const manifestPath = dir + "/page_client-reference-manifest.js";
    if (!seen.has(manifestPath) && existsSync(manifestPath)) {
      seen.add(manifestPath);
      paths.push(manifestPath);
    }
  }

  return paths;
}

/**
 * Build a map from request pathname → asset file path for static HTML pages.
 * Pages Router static pages need to be served from assets because their
 * handlers require filesystem access unavailable in CF Workers.
 *
 * Handles the /index → / normalization: outputs.staticFiles uses /index
 * as the pathname for the root page, but resolveRoutes resolves to /.
 */
function collectStaticPageMap(outputs: BuildContext["outputs"]): Record<string, string> {
  const map: Record<string, string> = {};
  for (const file of outputs.staticFiles) {
    // Only include HTML pages (no file extension), not _next/static/* assets
    if (!file.pathname.startsWith("/_next/") && !path.extname(file.pathname)) {
      const assetPath = path.join(file.pathname, "index.html");
      // Map the original pathname
      map[file.pathname] = assetPath;
      // Also map normalized form: /index → /, /foo/index → /foo
      if (file.pathname.endsWith("/index")) {
        const parent = file.pathname.slice(0, -6) || "/";
        map[parent] = assetPath;
      }
    }
  }
  return map;
}

function collectPathnames(outputs: BuildContext["outputs"]): string[] {
  const pathnames = new Set<string>();
  for (const p of outputs.appPages) pathnames.add(p.pathname);
  for (const r of outputs.appRoutes) pathnames.add(r.pathname);
  for (const p of outputs.pages) pathnames.add(p.pathname);
  for (const a of outputs.pagesApi) pathnames.add(a.pathname);
  for (const s of outputs.staticFiles) pathnames.add(s.pathname);
  return [...pathnames];
}

const NODE_BRIDGE_CODE = `
import { EventEmitter } from "node:events";
import { IncomingMessage as _IM, ServerResponse as _SR } from "http";
import { Socket } from "net";

// Extend built-in IncomingMessage with buffered body support.
// The built-in node:http IncomingMessage works for most cases but
// we need push() with deferred flowing for body buffering.
class IncomingMessage extends _IM {
  constructor() {
    super(new Socket());
    this._bufferedChunks = [];
    this._ended = false;
    this._customFlowing = false;
  }
  push(chunk) {
    if (chunk === null) {
      this._ended = true;
      if (this._customFlowing) { super.push(null); return; }
      return;
    }
    if (this._customFlowing) { super.push(chunk); return; }
    this._bufferedChunks.push(chunk);
  }
  _startFlowing() {
    if (this._customFlowing) return;
    this._customFlowing = true;
    for (const c of this._bufferedChunks) super.push(c);
    this._bufferedChunks = [];
    if (this._ended) super.push(null);
  }
  on(event, fn) {
    super.on(event, fn);
    if (event === "data" && !this._customFlowing) queueMicrotask(() => this._startFlowing());
    return this;
  }
  resume() { this._startFlowing(); return super.resume(); }
}
const ServerResponse = _SR;

/**
 * Streaming SSR bridge: Web Request -> IncomingMessage/ServerResponse -> Web Response.
 *
 * Uses TransformStream to stream chunks to the client as Next.js writes them.
 * The Response is returned as soon as headers are sent (writeHead/first write),
 * enabling Server Components streaming, PPR, and progressive rendering.
 */
async function invokeNodeHandler(request, mod, ctx, routeResult) {
  const url = new URL(request.url);

  // Read entire body first — async piping to IncomingMessage causes
  // timing issues where the handler reads before chunks arrive.
  let bodyBuffer = null;
  if (request.body) {
    const chunks = [];
    const reader = request.body.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(value);
    }
    if (chunks.length > 0) {
      const total = chunks.reduce((s, c) => s + c.length, 0);
      bodyBuffer = new Uint8Array(total);
      let offset = 0;
      for (const chunk of chunks) {
        bodyBuffer.set(chunk, offset);
        offset += chunk.length;
      }
    }
  }

  // Build IncomingMessage with body already buffered
  const req = new IncomingMessage();
  req.method = request.method;
  // Use invocationTarget URL if available (handles rewrites).
  // Strip $nxtPrest sentinel from optional catch-all paths — Next.js uses
  // this internally but the handler should receive the path without it.
  let targetUrl = routeResult?.invocationTarget?.pathname || url.pathname;
  targetUrl = targetUrl.replace(/\\/\\$nxtPrest/g, "").replace(/%24nxtPrest/gi, "") || targetUrl;
  const resolvedQuery = routeResult?.resolvedQuery || {};
  // Also strip sentinel from query params
  for (const [k, v] of Object.entries(resolvedQuery)) {
    if (v === "$nxtPrest" || v === "%24nxtPrest") resolvedQuery[k] = "";
  }
  const targetQuery = Object.keys(resolvedQuery).length > 0
    ? "?" + new URLSearchParams(resolvedQuery).toString()
    : url.search;
  req.url = targetUrl + targetQuery;
  req.headers = Object.fromEntries(request.headers);
  // Merge resolved headers from middleware into request headers
  if (routeResult?.resolvedHeaders) {
    routeResult.resolvedHeaders.forEach((val, key) => {
      req.headers[key.toLowerCase()] = val;
    });
  }
  if (bodyBuffer) {
    // Ensure Content-Length is set — body parsers need it.
    req.headers['content-length'] = String(bodyBuffer.length);
    req.push(bodyBuffer);
  }
  req.push(null);

  // Build ServerResponse with streaming output
  const res = new ServerResponse(req);
  const { readable, writable } = new TransformStream();
  const writer = writable.getWriter();

  // resolveResponse is called when we have enough info to return a Response
  // (status + headers). The body streams via the readable side.
  let resolveResponse;
  const responsePromise = new Promise((resolve) => { resolveResponse = resolve; });
  let headersFlushed = false;

  function flushHeaders() {
    if (headersFlushed) return;
    headersFlushed = true;
    // Build Headers manually to handle multi-value headers (Set-Cookie).
    const h = new Headers();
    for (const [key, val] of Object.entries(res.getHeaders())) {
      if (val === undefined) continue;
      if (Array.isArray(val)) {
        for (const v of val) h.append(key, String(v));
      } else {
        h.set(key, String(val));
      }
    }
    // Merge resolved headers from middleware (e.g., Set-Cookie, custom headers)
    if (routeResult?.resolvedHeaders) {
      routeResult.resolvedHeaders.forEach((val, key) => {
        if (key.toLowerCase() === "set-cookie") {
          h.append(key, val);
        } else if (!h.has(key)) {
          h.set(key, val);
        }
      });
    }
    resolveResponse(new Response(readable, {
      status: routeResult?.status || res.statusCode,
      statusText: res.statusMessage || "",
      headers: h,
    }));
  }

  // Track pending writes to prevent writer.close() racing with writes.
  let pendingWrites = Promise.resolve();

  // Intercept write — stream chunks to the client.
  // Chain writes through pendingWrites to avoid race conditions.
  res.write = function(chunk, encoding, cb) {
    if (typeof encoding === "function") { cb = encoding; encoding = undefined; }
    if (!headersFlushed) flushHeaders();
    if (chunk) {
      if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
      pendingWrites = pendingWrites
        .then(() => writer.write(chunk))
        .catch(() => {});
    }
    if (cb) pendingWrites.then(() => cb(), () => cb());
    return true;
  };

  // Intercept end — flush final chunk and close the stream.
  // Wait for all pending writes before closing.
  res.end = function(chunk, encoding, cb) {
    if (typeof chunk === "function") { cb = chunk; chunk = null; }
    if (typeof encoding === "function") { cb = encoding; encoding = null; }
    if (!headersFlushed) flushHeaders();
    if (chunk) {
      if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
      pendingWrites = pendingWrites
        .then(() => writer.write(chunk))
        .catch(() => {});
    }
    pendingWrites
      .then(() => writer.close())
      .catch(() => {})
      .then(() => {
        res.finished = true;
        res.emit("finish");
        res.emit("close");
        if (cb) cb();
      });
    return res;
  };

  // Intercept writeHead to flush headers early (enables 103 Early Hints)
  const origWriteHead = res.writeHead.bind(res);
  res.writeHead = function(...args) {
    origWriteHead(...args);
    flushHeaders();
    return res;
  };

  // Invoke the handler — try multiple export patterns:
  // - mod.handler: standard Next.js handler export (app pages, routes)
  // - mod.routeModule.handle: route module instance method
  // - mod.default: default export (some module formats)
  // - mod.default.default: CJS interop nested default
  let handlerFn = mod.handler
    || mod.routeModule?.handle?.bind(mod.routeModule)
    || (typeof mod.default === "function" ? mod.default : null)
    || (typeof mod.default?.default === "function" ? mod.default.default : null);

  // If module only exports default (no handler/routeModule), it's likely an
  // edge-style handler that takes (Request, ctx) → Response. Call directly
  // instead of going through Node.js IncomingMessage bridge.
  if (typeof handlerFn === "function" && !mod.handler && !mod.routeModule
      && Object.keys(mod).length <= 2) {
    try {
      const edgeResult = await handlerFn(request, { waitUntil: ctx.waitUntil.bind(ctx) });
      if (edgeResult instanceof Response) {
        writer.close().catch(() => {});
        return edgeResult;
      }
    } catch {}
    // If it didn't return a Response, fall through to Node bridge
  }

  if (typeof handlerFn !== "function") {
    writer.close().catch(() => {});
    throw new Error("No handler function found on module (keys: " + Object.keys(mod).join(",") + ")");
  }

  // Safety timeout: force-close the body stream if the handler never calls
  // res.end(). Prevents ERR_INCOMPLETE_CHUNKED_ENCODING hangs.
  const bodyTimeout = setTimeout(() => {
    if (!res.finished) {
      res.finished = true;
      pendingWrites
        .then(() => writer.close())
        .catch(() => {});
    }
  }, 30000);

  try {
    const handlerResult = handlerFn(req, res, {
      waitUntil: (p) => ctx.waitUntil(p.catch(() => {})),
      params: routeResult?.routeMatches || {},
      requestMeta: {
        relativeProjectDir: ".",
        hostname: request.headers.get("host") || "localhost",
      },
    });

    // Swallow handler rejection to prevent CF Workers 1101.
    // The actual response data is captured via res.write/end.
    if (handlerResult?.then) {
      handlerResult.catch((err) => {
        if (!res.finished) {
          res.statusCode = 500;
          res.end(JSON.stringify({ error: "render_error", message: err instanceof Error ? err.message : String(err) }));
        }
      });
    }
  } catch (err) {
    // Handle synchronous handler errors
    if (!res.finished) {
      res.statusCode = 500;
      res.end(JSON.stringify({ error: "render_error", message: err instanceof Error ? err.message : String(err) }));
    }
  }

  // Clear body timeout once res.end() is called
  const origEmit = res.emit.bind(res);
  res.emit = function(event, ...args) {
    if (event === "finish") clearTimeout(bodyTimeout);
    return origEmit(event, ...args);
  };

  // Wait for the Response to be created (headers flushed), with timeout
  const response = await Promise.race([
    responsePromise,
    new Promise((_, reject) => setTimeout(() => {
      writer.close().catch(() => {});
      reject(new Error("SSR timeout: no response headers within 60s"));
    }, 60000)),
  ]);

  return response;
}
`;
